apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql-statefullset
  namespace: bank
  labels:
    app: bankapp
spec:
  serviceName: mysql
  replicas: 2
  selector:
    matchLabels:
      app: bankapp
  template:
    metadata:
      labels:
        app: bankapp
    spec:
      containers:
        - name: sql-pod
          image: mysql:latest
          ports:
            - containerPort: 3306
          env:
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: bank-secret
                key: MYSQL_ROOT_PASSWORD
          - name: MYSQL_DATABASE
            valueFrom:
              configMapKeyRef:
                name: bank-config
                key: MYSQL_DATABASE
          volumeMounts:
          - name: mysql
            mountPath: /var/lib/mysql
  volumeClaimTemplates:
  - metadata:
      name: mysql
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 10Gi
      storageClassName: standard  # Must match the PV storageClassName
