kind: PersistentVolume
apiVersion: v1
metadata:
  name: bank-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  hostPath:
    path: '/tmp/bankapp-msql'
