apiVersion: v1
kind: PersistentVolume
metadata:
  name: bank-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  hostPath:
    path: '/tmp/bankapp-msql'
