apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bank-pvc
spec:
  resources:
    requests:
      storage: 10Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  volumeName: bank-pv  # Manually bind the PVC to the PV
